//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRadar.Plugin.CustomContent {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomContentStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRadar.Plugin.CustomContent.CustomContentStrings", typeof(CustomContentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At 的本地化字符串。
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is already a site root folder 的本地化字符串。
        /// </summary>
        public static string DirectoryAlreadyInUse {
            get {
                return ResourceManager.GetString("DirectoryAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not exist 的本地化字符串。
        /// </summary>
        public static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled, no site root folder specified 的本地化字符串。
        /// </summary>
        public static string EnabledNoSiteRoot {
            get {
                return ResourceManager.GetString("EnabledNoSiteRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled, serving custom content from {0} 的本地化字符串。
        /// </summary>
        public static string EnabledWithSiteRoot {
            get {
                return ResourceManager.GetString("EnabledWithSiteRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error caught while checking filename: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorCheckingFileName {
            get {
                return ResourceManager.GetString("ErrorCheckingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error caught while checking folder: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorCheckingFolder {
            get {
                return ResourceManager.GetString("ErrorCheckingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} does not exist 的本地化字符串。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the name of the file to inject into the HTML 的本地化字符串。
        /// </summary>
        public static string FileNameRequired {
            get {
                return ResourceManager.GetString("FileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML page 的本地化字符串。
        /// </summary>
        public static string HtmlPage {
            get {
                return ResourceManager.GetString("HtmlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject 的本地化字符串。
        /// </summary>
        public static string Inject {
            get {
                return ResourceManager.GetString("Inject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject file 的本地化字符串。
        /// </summary>
        public static string InjectFile {
            get {
                return ResourceManager.GetString("InjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inject into HTML 的本地化字符串。
        /// </summary>
        public static string InjectHtml {
            get {
                return ResourceManager.GetString("InjectHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Of 的本地化字符串。
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the HTMLfile to inject content into must end in .htm or .html 的本地化字符串。
        /// </summary>
        public static string PathAndFileMissingExtension {
            get {
                return ResourceManager.GetString("PathAndFileMissingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The address of the HTML page must start with a forward-slash 的本地化字符串。
        /// </summary>
        public static string PathAndFileMissingRoot {
            get {
                return ResourceManager.GetString("PathAndFileMissingRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the path and name of the HTML file to inject content into (e.g. /index.html) or * to inject into all HTML 的本地化字符串。
        /// </summary>
        public static string PathAndFileRequired {
            get {
                return ResourceManager.GetString("PathAndFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace / add site content 的本地化字符串。
        /// </summary>
        public static string ReplaceAndAddSiteContent {
            get {
                return ResourceManager.GetString("ReplaceAndAddSiteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site root folder 的本地化字符串。
        /// </summary>
        public static string SiteRootLabel {
            get {
                return ResourceManager.GetString("SiteRootLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
