/*
 * Globalize Culture zh-HK
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo("zh-HK", "default", {
    name: "zh-HK",
	englishName: "Chinese (HongKong)",
	nativeName: "中文 (香港)",
	numberFormat: {
		currency: {
		    pattern: ["$-n", "$n"],
			symbol: "HK$"
		}
	},
	calendars: {
		standard: {
			firstDay: 1,
			patterns: {
			    d: "yyyy/MM/dd",
			    D: "yyyy MMMM dd",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "yyyy MMMM dd HH:mm",
				F: "yyyy MMMM dd HH:mm:ss",
				M: "MMMM dd",
				Y: "yyyy MMMM"
			}
		}
	}
});

}( this ));